-- 0011_password_setup_tokens.sql — invitation and password-reset links.
-- Owner: Dev A (identity)
--
-- An administrator creates an account without a password; the person sets their
-- own via a emailed link. This table is what makes that link safe.
--
-- Three properties it has to have, and the columns that give each one:
--
--   single use   `used_at` — a link in an inbox is forever, so it must stop
--                working the moment it is redeemed
--   expiring     `expires_at` — an unredeemed invite left in a mailbox for six
--                months should not still open the door
--   unguessable  the token is 32 random bytes, generated by the application
--
-- The token itself is NOT stored. `token_hash` holds a SHA-256 of it, for the
-- same reason `password_hash` exists: whoever reads this table must not come
-- away able to sign in as anybody. SHA-256 rather than bcrypt is deliberate —
-- the input is 256 bits of entropy, so there is no dictionary to attack and no
-- reason to pay bcrypt's cost on every link click.

CREATE TABLE password_setup_tokens (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id  uuid NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
  -- SHA-256 hex of the token handed to the user. Unique so a lookup is one
  -- index probe and a (theoretical) collision cannot authenticate two people.
  token_hash  text NOT NULL,
  /**
   * What the link is for. Both flows issue the same kind of token; the purpose
   * only changes the wording of the email and the heading on the page.
   */
  purpose     text NOT NULL DEFAULT 'invite',
  expires_at  timestamptz NOT NULL,
  used_at     timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT setup_tokens_hash_key UNIQUE (token_hash),
  CONSTRAINT setup_tokens_purpose_valid CHECK (purpose IN ('invite', 'reset')),
  CONSTRAINT setup_tokens_expiry_future CHECK (expires_at > created_at)
);

-- Issuing a new link invalidates the outstanding ones for that person, which
-- is a delete-then-insert against this index.
CREATE INDEX setup_tokens_account_idx ON password_setup_tokens (account_id);

-- Housekeeping: find everything expired or spent.
CREATE INDEX setup_tokens_expiry_idx ON password_setup_tokens (expires_at)
  WHERE used_at IS NULL;

COMMENT ON COLUMN password_setup_tokens.token_hash IS
  'SHA-256 of the emailed token. The token itself is never stored.';
